server:
  port: 8989  #端口号
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #连接池
    url: jdbc:mysql://localhost:3306/snackshop   #数据库
    username: root  #账户
    password: 123456  #密码
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #SQL日志打印 #端口号